//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsStorage.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public long FilmId { get; set; }
        public string FilmName { get; set; }
        public int Release { get; set; }
        public int fk_GenreID { get; set; }
        public int fk_UserID { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
        public string fileDescription { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual User User { get; set; }
    }
}
