//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsStorage.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Film
    {
        public long FilmID { get; set; }
        public string FilmName { get; set; }
        public int Release { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string fileDescription { get; set; }
        public int GenreID { get; set; }
        public string GenreName { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
    }
}
